logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
#    org.springframework.security: DEBUG
#    org.thymeleaf: DEBUG
    com.example: DEBUG
    

# 帳票出力機能の設定
report:
# コンパイル済の様式ファイルを保管する一時ディレクトリを変更する場合に設定
#  jasper-file-tmpdir: jasper2
# PDFを一時保存するディレクトリを変更する場合に設定
#  report-tmpdir: pdf2
#  delete-tempfiles-initial-delay-seconds: 60
#  delete-tempfiles-fixed-rate-seconds: 60
