spring:
  application:
    name: sample-jasperreports-springboot
  profiles:
    active:
    - dev
    - log_default  #logging in default format
#    - log_container  #logging in json format    

  messages:
    basename: messages, messages-fw-common, messages-fw-web


# 帳票出力機能の設定
#example: 
#  report:
# PDFの権限拒否設定
#    pdf-permission-denied: COPY|PRINTING|MODIFY_CONTENTS
#    pdf-permission-denied: ALL
# PDFの暗号化レベル設定
#    128bit-key: false
