AWSTemplateFormatVersion: 2010-09-09
Description: KMS Template for CloudFormation Demo.
#Metadata: 

Parameters:
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  KeyAliasName:
    Type: String
    Description: "KMS Key Alias"
    Default: "alias/digital-signature-key"    
  IsMultiRegion:
    Type: String
    Description: "KMS Key MultiRegion"
    Default: "true"
    AllowedValues: ["true", "false"]
  PendingWindowInDaysValue:
    Type: Number
    Description: "KMS Key Pending Window In Days"
    Default: 7
    AllowedValues: [7, 30]        
  UpdateReplacePolicyValue:
    Type: String
    Description: "KMS Key Update Replace Policy"
    Default: "Delete" #開発用
    AllowedValues: ["Delete", "Retain"]
  UserName:
    Type: String
    Description: "IAM User Name who can use this KMS Key"
    Default: "Administrator" #適宜変更すること

#Mappings: 

#Conditions: 

Resources:
  # KMS Key
  KMSKey:
    Type: AWS::KMS::Key
    Properties:     
      Description: "KMS Key for Digital Signature"
      KeySpec: "ECC_NIST_P256"
      KeyUsage: "SIGN_VERIFY"
      Enabled: true
      MultiRegion: !Ref IsMultiRegion
      PendingWindowInDays: !Ref PendingWindowInDaysValue
      # 適宜修正すること
      KeyPolicy:
        Version: 2012-10-17
        Id: demo-key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'          
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:user/${UserName}
            Action: 'kms:*'
            Resource: '*'
    UpdateReplacePolicy: !Ref UpdateReplacePolicyValue
    DeletionPolicy: Retain

  # KMS Key Alias
  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Ref KeyAliasName
      TargetKeyId: !Ref KMSKey
        
Outputs:
  KMSKeyId:
    Description: "KMS Key ID"
    Value: !Ref KMSKey
    Export:
      Name: !Sub "${StackPrefix}-KMSKeyId"
  KMSKeyArn:
    Description: "KMS Key ARN"
    Value: !GetAtt KMSKey.Arn
    Export:
      Name: !Sub "${StackPrefix}-KMSKeyArn"
  KMSKeyAliasName:
    Description: "KMS Key Alias Name"
    Value: !Ref KMSKeyAlias
    Export:
      Name: !Sub "${StackPrefix}-KMSKeyAliasName"
