AWSTemplateFormatVersion: 2010-09-09
Description: KMS Replica Key Template for CloudFormation Demo.
#Metadata:

Parameters: 
  PrimaryKeyArn:
    Description: "KMS Primary Key ARN"
    Type: String
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  KeyAliasName:
    Type: String
    Description: "KMS Key Alias"
    Default: "alias/digital-signature-key"
  PendingWindowInDaysValue:
    Type: Number
    Description: "KMS Key Pending Window In Days"
    Default: 7
    AllowedValues: [7, 30]
  UpdateReplacePolicyValue:
    Type: String
    Description: "KMS Key Update Replace Policy"
    Default: "Delete" #開発用
    AllowedValues: ["Delete", "Retain"]
  UserName:
    Type: String
    Description: "IAM User Name who can use this KMS Key"
    Default: "Administrator" #適宜変更すること

#Mappings: 

#Conditions: 

Resources: 
  # KMS Replica Key
  KMSReplicaKey:
    Type: AWS::KMS::ReplicaKey
    Properties:
      Description: "KMS Replica Key for Digital Signature"
      PrimaryKeyArn: !Ref PrimaryKeyArn        
      PendingWindowInDays: !Ref PendingWindowInDaysValue
      # 適宜修正すること
      KeyPolicy:
        Version: 2012-10-17
        Id: demo-key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'          
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:user/${UserName}
            Action: 'kms:*'
            Resource: '*'
    UpdateReplacePolicy: !Ref UpdateReplacePolicyValue
    DeletionPolicy: Retain


  # KMS Key Alias
  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Ref KeyAliasName
      TargetKeyId: !Ref KMSReplicaKey

Outputs:
  KMSKeyId:
    Description: "ID of the KMS Replica Key"
    Value: !Ref KMSReplicaKey
  KMSReplicaKeyArn:
    Description: "ARN of the KMS Replica Key"
    Value: !GetAtt KMSReplicaKey.Arn
  KMSKeyAliasName:
    Description: "KMS Key Alias Name"
    Value: !Ref KMSKeyAlias
    Export:
      Name: !Sub "${StackPrefix}-KMSKeyAliasName"    